### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by Mohd306** [naver/hammer.js#27]
Hello my friends,

i hope you are doing well,
im having an issue while making up my project, im using windows 7 32bit

knowing that i tried npm i -h
 but still the same

please check the image below
https://i.imgur.com/KwxHYc9.jpg

is it maybe because im using windows 32bit??

regards

any help?

**Comment by WoodNeck** [comment]
Hello, @Mohd306!
It looks like Node can't find any git.
Check that git is installed & added on the env variable PATH.
See also #26, it is basically the same issue :)

**Comment by Mohd306** [comment]
Hello,
i did installed git, but still the same thing!!

**Comment by WoodNeck** [comment]
Make sure you can use the command `git` in your terminal. (cmd.exe for your case)
Please search for StackOverflow about `spawn git ENOENT`, I think you can find the fix for you there.
Sorry but I think this is not an issue for hammer.js but your env setting, so I'll close the issue for now.
Feel free to reopen it if you sure it's hammer.js issue :)
